name: project
description: "A new Flutter project."
publish_to: 'none'

version: 1.3.2+3

environment:
  sdk: '>=3.2.6 <4.0.0' # Flutterのバージョンが3.2.6以上であればこのままでOK

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8 # 最新版に更新
  webview_flutter: ^4.7.0 # 最新版なのでこのまま
  in_app_purchase: ^3.2.0 # 最新版なのでこのまま
  logger: ^2.2.0 # 最新版なのでこのまま
  appsflyer_sdk: ^6.16.2 # 最新版なのでこのまま
  app_tracking_transparency: ^2.0.6+1
  http: ^1.2.1 # 最新版に更新
  in_app_purchase_storekit: ^0.3.14 # 最新版なのでこのまま
  in_app_purchase_android: ^0.3.6+13 # 最新版なのでこのまま
  flutter_launcher_icons: ^0.13.1 # 最新版なのでこのまま

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0 # 最新版なのでこのまま

flutter:
  uses-material-design: true

  assets:
    - datas/
    - shorebird.yaml
